go_import_path: github.com/kevinburke/nacl

language: go

os: linux
dist: trusty

sudo: required

before_script:
     - make install-travis

script:
  - make ci
  - ls -al bazel-out/host/bin/external/go_stdlib_linux_amd64_cgo_race || true
  - du -sh $HOME/.cache/bazel/_bazel_travis/*
  - make clean-cache
  - du -sh $HOME/.cache/bazel/_bazel_travis/*

cache:
  directories:
    - $HOME/.bzrepos
    - $HOME/.cache/bazel
